# Generated by Django 3.1.7 on 2021-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenateBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('prime_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('all_sponsors', models.TextField(blank=True, max_length=255, null=True)),
                ('last_action', models.TextField(blank=True, null=True)),
                ('memo_title', models.TextField(blank=True, null=True)),
                ('memo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('bill_text', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
