# Generated by Django 3.1.7 on 2021-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senatebills',
            name='date_introduced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='senatebills',
            name='prime_sponsor_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
