# Generated by Django 3.1.7 on 2021-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_senateresolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('date_introduced', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('prime_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('prime_sponsor_url', models.URLField(blank=True, max_length=255, null=True)),
                ('all_sponsors', models.TextField(blank=True, max_length=255, null=True)),
                ('last_action', models.TextField(blank=True, null=True)),
                ('memo_title', models.TextField(blank=True, null=True)),
                ('memo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('bill_text', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseResolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_number', models.IntegerField()),
                ('date_introduced', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('prime_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('prime_sponsor_url', models.URLField(blank=True, max_length=255, null=True)),
                ('all_sponsors', models.TextField(blank=True, max_length=255, null=True)),
                ('last_action', models.TextField(blank=True, null=True)),
                ('memo_title', models.TextField(blank=True, null=True)),
                ('memo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('resolution_text', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
